# Generated by Django 5.0.7 on 2026-05-18 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_audit', models.CharField(choices=[('QUALITE', 'Audit qualité'), ('SECURITE', 'Audit sécurité'), ('PRODUCTION', 'Audit production'), ('MAINTENANCE', 'Audit maintenance')], max_length=30)),
                ('texte', models.CharField(max_length=255)),
                ('ordre', models.PositiveIntegerField(default=1)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Point de checklist',
                'verbose_name_plural': 'Points de checklist',
                'ordering': ['type_audit', 'ordre'],
            },
        ),
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150)),
                ('type_audit', models.CharField(choices=[('QUALITE', 'Audit qualité'), ('SECURITE', 'Audit sécurité'), ('PRODUCTION', 'Audit production'), ('MAINTENANCE', 'Audit maintenance')], default='QUALITE', max_length=30)),
                ('date_audit', models.DateField()),
                ('statut', models.CharField(choices=[('PLANIFIE', 'Planifié'), ('EN_COURS', 'En cours'), ('TERMINE', 'Terminé')], default='PLANIFIE', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, help_text='Client ou département demandeur concerné par cet audit.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audits_client', to=settings.AUTH_USER_MODEL)),
                ('auditeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audits_affectes', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audits_crees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_audit'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('RESPONSABLE', 'Responsable Audit'), ('AUDITEUR', 'Auditeur'), ('CLIENT', 'Client')], default='AUDITEUR', max_length=20)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports', to='audit.audit')),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapports_rediges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est_conforme', models.BooleanField(default=False)),
                ('remarque', models.CharField(blank=True, max_length=255)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audit.checklistitem')),
                ('rapport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_reponses', to='audit.rapport')),
            ],
            options={
                'verbose_name': 'Réponse checklist',
                'verbose_name_plural': 'Réponses checklist',
            },
        ),
    ]
