# Generated by Django 5.0.7 on 2026-06-13 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklistresponse',
            name='est_conforme',
        ),
        migrations.AddField(
            model_name='checklistresponse',
            name='statut',
            field=models.CharField(choices=[('CONFORME', 'Conforme'), ('NON_CONFORME', 'Non conforme'), ('INDISPONIBLE', 'Indisponible')], default='CONFORME', max_length=20),
        ),
    ]
