# Generated by Django 5.2.17 on 2026-09-24 17:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_audit_types_client_register'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
            ],
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, unique=True, verbose_name='Nom')),
            ],
        ),
        migrations.AddField(
            model_name='audit',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Échéance'),
        ),
        migrations.AddField(
            model_name='audit',
            name='priority',
            field=models.CharField(choices=[('CRITICAL', 'Critique'), ('HIGH', 'Élevé'), ('MEDIUM', 'Modéré'), ('LOW', 'Faible')], default='MEDIUM', max_length=10, verbose_name='Risque'),
        ),
        migrations.AddField(
            model_name='audit',
            name='progress',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Progression (%)'),
        ),
        migrations.AddField(
            model_name='audit',
            name='stage',
            field=models.CharField(choices=[('PLANNING', 'Planification'), ('FIELDWORK', 'Travaux terrain'), ('REVIEW', 'Revue'), ('REPORTING', 'Rapport'), ('CLOSED', 'Clôture')], default='PLANNING', max_length=20, verbose_name='Étape'),
        ),
        migrations.AddField(
            model_name='audit',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='audit.department', verbose_name='Département'),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('file', models.FileField(upload_to='audit_documents/%Y/%m/', verbose_name='Fichier')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='audit.audit', verbose_name='Mission')),
            ],
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Constat')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('priority', models.CharField(choices=[('CRITICAL', 'Critique'), ('HIGH', 'Élevé'), ('MEDIUM', 'Modéré'), ('LOW', 'Faible')], default='MEDIUM', max_length=10, verbose_name='Gravité')),
                ('resolved', models.BooleanField(default=False, verbose_name='Résolu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='audit.audit', verbose_name='Mission')),
            ],
        ),
        migrations.CreateModel(
            name='CorrectiveAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Action')),
                ('description', models.TextField(blank=True, verbose_name='Description / preuve')),
                ('priority', models.CharField(choices=[('CRITICAL', 'Critique'), ('HIGH', 'Élevé'), ('MEDIUM', 'Modéré'), ('LOW', 'Faible')], default='MEDIUM', max_length=10, verbose_name='Priorité')),
                ('due_date', models.DateField(verbose_name='Échéance')),
                ('state', models.CharField(choices=[('OPEN', 'Ouverte'), ('IN_PROGRESS', 'En cours'), ('EVIDENCE', 'Preuve attendue'), ('COMPLETED', 'Terminée')], default='OPEN', max_length=20, verbose_name='État')),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='audit.audit', verbose_name='Mission')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
                ('finding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='audit.finding', verbose_name='Constat associé')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='audit.organisation', verbose_name='Organisation'),
        ),
        migrations.AddField(
            model_name='audit',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='audit.organisation', verbose_name='Organisation'),
        ),
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Risque')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('impact', models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Impact (1–5)')),
                ('likelihood', models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Probabilité (1–5)')),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='audit.audit', verbose_name='Mission')),
                ('findings', models.ManyToManyField(blank=True, to='audit.finding', verbose_name='Constats associés')),
            ],
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('organisation', 'nom'), name='department_name_per_org'),
        ),
    ]
